services:
  - type: web
    name: einkaufsliste-projekt
    env: python

    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      chmod +x base.sh && ./base.sh

    startCommand: gunicorn config.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0