# Generated by Django 5.2.12 on 2026-04-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Leer lassen, wenn vorhanden, aber Menge unbekannt ist.', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, choices=[('g', 'Gramm'), ('kg', 'Kilogramm'), ('ml', 'Milliliter'), ('l', 'Liter'), ('pcs', 'Stück'), ('el', 'Esslöffel'), ('tl', 'Teelöffel')], help_text='Optional. Wird vor allem genutzt, wenn eine Menge angegeben ist.', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='households.household')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='ingredients.ingredient')),
            ],
            options={
                'ordering': ['ingredient__name'],
                'unique_together': {('household', 'ingredient')},
            },
        ),
    ]
