# Generated by Django 5.2.12 on 2026-06-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'Gramm'), ('kg', 'Kilogramm'), ('ml', 'Milliliter'), ('l', 'Liter'), ('pcs', 'Stück'), ('pkg', 'Packung'), ('el', 'Esslöffel'), ('tl', 'Teelöffel')], help_text='Optional. Wird vor allem genutzt, wenn eine Menge angegeben ist.', max_length=10),
        ),
    ]
