# Generated by Django 5.2.12 on 2026-03-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shoppinglistitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='source_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
