# Generated by Django 5.2.12 on 2026-05-31 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch', 'Mittagessen'), ('dinner', 'Abendessen')], max_length=10)),
                ('recurrence', models.CharField(choices=[('none', 'Einmalig'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich')], default='none', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='households.household')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='recipes.recipe')),
            ],
            options={
                'ordering': ['date', 'meal'],
            },
        ),
    ]
