# Generated by Django 5.2.12 on 2026-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_unit', models.CharField(choices=[('g', 'Gramm'), ('kg', 'Kilogramm'), ('ml', 'Milliliter'), ('l', 'Liter'), ('pcs', 'Stück'), ('el', 'Esslöffel'), ('tl', 'Teelöffel')], default='g', max_length=10)),
                ('category', models.CharField(choices=[('spices', 'Gewürze'), ('fridge', 'Kühlschrank'), ('drinks', 'Getränke'), ('pantry', 'Vorrat'), ('freezer', 'Tiefkühl'), ('baking', 'Backzutaten'), ('snacks', 'Snacks'), ('other', 'Sonstiges')], default='other', max_length=20)),
            ],
        ),
    ]
