# Generated by Django 5.2.12 on 2026-06-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('fruit_veg', 'Obst & Gemüse'), ('spices', 'Gewürze'), ('fridge', 'Kühlschrank'), ('drinks', 'Getränke'), ('pantry', 'Vorrat'), ('freezer', 'Tiefkühl'), ('baking', 'Backzutaten'), ('snacks', 'Snacks'), ('other', 'Sonstiges')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(choices=[('g', 'Gramm'), ('kg', 'Kilogramm'), ('ml', 'Milliliter'), ('l', 'Liter'), ('pcs', 'Stück'), ('pkg', 'Packung'), ('el', 'Esslöffel'), ('tl', 'Teelöffel')], default='g', max_length=10),
        ),
    ]
