# Generated by Django 5.2.12 on 2026-03-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_default_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('spices', 'Gewürze'), ('fridge', 'Kühlschrank'), ('drinks', 'Getränke'), ('pantry', 'Vorrat'), ('freezer', 'Tiefkühl'), ('baking', 'Backzutaten'), ('snacks', 'Snacks'), ('other', 'Sonstiges')], default='other', max_length=20),
        ),
    ]
