# Generated by Django 5.2.12 on 2026-03-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('spices', 'Gewürze'), ('fridge', 'Kühlschrank'), ('drinks', 'Getränke'), ('pantry', 'Vorrat'), ('freezer', 'Tiefkühl'), ('baking', 'Backzutaten'), ('other', 'Sonstiges')], default='other', max_length=20),
        ),
    ]
