# Generated by Django 5.2.12 on 2026-04-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0005_alter_ingredient_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'unique_together': {('name', 'location', 'postal_code')},
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_text', models.CharField(blank=True, max_length=100)),
                ('product_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='ingredients.ingredient')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.dealsource')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.store')),
            ],
            options={
                'ordering': ['store__name', 'title'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
