# Generated by Django 5.2.12 on 2026-05-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='deal',
            name='product_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
